In [1]:
import pandas as pd
import seaborn as sns
from sklearn.decomposition import PCA
import matplotlib
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier           
from sklearn.neighbors import KNeighborsClassifier            
from sklearn.ensemble import GradientBoostingClassifier       
from sklearn.neural_network import MLPClassifier
#from sklearn.model_selection import GridSearchCV 
from sklearn import tree
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn import tree
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
import numpy as np
from sklearn.preprocessing import StandardScaler
import statsmodels.api as sm

import statsmodels.formula.api as smf

In [2]:
encuesta=pd.read_csv("../trabajo final macroencuesta/DA3242",delimiter= '\t', header=None)

In [3]:
#Creamos el diccionario con el nombre de las columnas y donde se realizan los cortes 
columnas={"ESTU": [1,4], "CUES": [5,9], "CCAA":[10,11], "PROV": [12,13], "MUN": [14,16], "TAMUNI": [17,17], "CAPITAL": [18,18], "DISTR": [19,20], "SECCION": [21,23],"ENTREV": [24,27], "P0A": [28,28], "P1": [29,29], "P2": [30,30], "P3": [31,31], "P4": [32,32], "P501": [33,33], "P502": [34,34], "P503": [35,35], "P601": [36,37], "P602": [38,39], "P603": [40,41],"P701": [42,43], "P702": [44,45], "P703": [46,47], "P801": [48,48], "P802": [49,49], "P803": [50,50], "P804": [51,51], "P805": [52,52], "P806": [53,53], "P807": [54,54], "P808": [55,55],"P809": [56,56], "P810": [57,57], "P811": [58,58], "P812": [59,59], "P813": [60,60], "P814":[61,61], "P815": [62,62], "P816": [63,63], "P9": [64,64], "P9A":[65,65], "P9B01": [66,67], "P9B02": [68,69],"P10": [70,71], "P10A": [72,73], "P1101": [74,75], "P1102": [76,77], "P1103": [78,79], "P1104": [80,81], "P1105": [82,83], "P1106": [84,85],"P12":[86,87], "P1301": [88,89], "P1302": [90,91], "P1303": [92,93], "P1304": [94,95], "P1305": [96,97], "P1306": [98,99], "P1307": [100,101],"P1308": [102,103], "P1309": [104,105], "P1310": [106,107], "P1311": [108,109], "P1312": [110,111], "P1313": [112,113], "P1314": [114,115],"P1315": [116,117], "P1316": [118,119], "P1317": [120,121], "P1318": [122,123], "P1319": [124,125], "P1320": [126,127], "P14": [128,129],"P15": [130,131], "P16": [132,133], "P17": [134,135], "P18": [136,136], "P18A": [137,138], "P19": [139,140], "P2001": [141,142], "P2002": [143,144],"P2003": [145,146], "P2004" :[147,148], "P2005": [149,150], "P2006": [151,152], "P2007": [153,154], "P2008": [155,156],"P2009": [157,158],"P2010": [159,160], "P2011": [161,162], "P2012": [163,164], "P2013": [165,166], "P2014": [167,168], "P2015": [169,170], "P2016": [171,172],"P2017": [173,174], "P2018": [175,176], "P2019": [177,178], "P2020": [179,180], "P21": [181,182], "P21A": [183,184], "P22": [185,185], "P23": [186,187],"P24": [188,188], "P24A": [189,190], "P25": [191,191], "P25A":[192,193], "P26":[194,194], "P27": [195,195], "P28": [196,196], "P29": [197,197], "P30": [198,198], "P30A": [199,199], "P31":[200,200],"E101": [201,202], "E102": [203,204], "E103": [205,206], "E2": [207,209], "E3": [210,210], "C1": [211,211], "C1A": [212,213], "PESO": [214,220],"P9BCOMR": [221,224], "P10R": [225,226], "P10AR": [227,228], "VOTOSIMG": [229,230], "P18AR": [231,232], "RECUERDO": [233,234], "P9BCOM": [235,238],"P14R": [239,240], "P15R": [241,242], "P16R": [243,244], "ESTUDIOS": [245,245], "PESOCCAA": [246,252]}

In [4]:
#aplicamos los intervalos del diccionario en el dataFrame que hemos obtenido para poder crear las columnas
def get_intervals(x, a, b): 
    try: 
        return x[a:b]
    except: 
        print(x, a, b)

for a in columnas:
    encuesta[a] = encuesta[0].apply(lambda x: get_intervals(x, columnas[a][0]-1, columnas[a][1]))
encuesta.head()

0 P1106 P1302 P1304 P2001  \
0  3242    116 1 5951 0  0   01124321313 818 8121...     2     3     0     7   
1  3242    216 1 5951 0  0   012333128 11898 1451...     3     2     3     6   
2  3242    316 1 5951 0  0   014454799 1192219229...     1     0     0    98   
3  3242    416 1 5951 0  0   01133317919 198 1 91...     3     5     0     7   
4  3242    516 1 5951 0  0   099939138 1181212189...     4     3     3     5   

  P2016 P816 P1103 P9B02 P801  ... P1318 P1101 P814 P503 P703 P702 P1312 P15  \
0     0    8     2     0    4  ...          97    8    3   13   12     0   1   
1     0    8     2     0    2  ...           3    8    8   18   45     0   1   
2     0    5     1     0    5  ...           1    5    9   98   22     0  98   
3     0    8     2     0    5  ...           1    8    9   18    9     1   1   
4     0    8     4     0    3  ...           5    8    8   98   18     1   1   

  ENTREV P29  
0      0   1  
1      0   4  
2      0   2  
3      0   2  
4      0   2  

[5 rows x 136 columns]

In [5]:
#Eliminamos la columna 0, dado que ya no nos sirve
def drop_columna(data,columna,axis=1,inplace=True):
    return data.drop(columna, axis=1, inplace=True)
drop_columna(encuesta,0)

In [6]:
#convertimos las columnas en numericas 
def get_numeric(x):
    try:
        return int(x)
    except:
        return 0
for a in columnas:
    encuesta[a] = encuesta[a].apply(get_numeric)
    
encuesta.head()

P1106  P1302  P1304  P2001  P2016  P816  P1103  P9B02  P801  P2007  ...  \
0      2      3      0      7      0     8      2      0     4     98  ...   
1      3      2      3      6      0     8      2      0     2     98  ...   
2      1      0      0     98      0     5      1      0     5     98  ...   
3      3      5      0      7      0     8      2      0     5      3  ...   
4      4      3      3      5      0     8      4      0     3     98  ...   

   P1318  P1101  P814  P503  P703  P702  P1312  P15  ENTREV  P29  
0      0     97     8     3    13    12      0    1       0    1  
1      0      3     8     8    18    45      0    1       0    4  
2      0      1     5     9    98    22      0   98       0    2  
3      0      1     8     9    18     9      1    1       0    2  
4      0      5     8     8    98    18      1    1       0    2  

[5 rows x 135 columns]

In [7]:
#seleccionamos las columnas que no nos interesan
columnas_para_eliminar=("ESTU","CUES","PROV","MUN","DISTR","SECCION","ENTREV","P501","P502","P503","P601","P602","P603","P701","P702","P703","P805","P806","P807","P808","P809","P810","P811","P812","P813","P814","P815","P816","P9","P9A","P9B01","P9B02","P10","P1101","P1102","P1103","P1104","P1105","P1106","P1305","P1306","P1307","P1308","P1309","P1310","P1311","P1312","P1313","P1314","P1315","P1316","P1317","P1318","P1319","P1320","P14","P15","P16","P17","P18","P18A","P2005","P2006","P2007","P2008","P2009","P2010","P2011","P2012","P2013","P2014","P2015","P2016","P2017","P2018","P2019","P2020","P21","P21A","P24A","P25A","P29","P30","P30A","P31","E101","E102","E103","E2","E3","C1","C1A","VOTOSIMG","RECUERDO","P9BCOM","P15R","P16R","P10AR","P9BCOMR","P10A","P24","P10R","P12","P18AR","PESO","PESOCCAA")
for a in columnas_para_eliminar:
    drop_columna(encuesta,a)

In [8]:
cols=["P1","P2","P3","P4","P801","P802","P803","P804","P1301","P1302","P1303","P1304","P2001","P2002","P2003","P2004","P23","TAMUNI","ESTUDIOS","CAPITAL","CCAA","P0A","P14R","P22","P25","P26","P27","P28","P19"]
colssincat=["P1","P2","P3","P4","P801","P802","P803","P804","P1301","P1302","P1303","P1304","P2001","P2002","P2003","P2004","P23","TAMUNI","ESTUDIOS","ideologia"]

In [9]:
encuesta = encuesta[cols]

In [10]:
limpieza9=("ESTUDIOS","P0A","P1","P2","P3","P4","P801","P802","P803","P804","P23","P25","P26","P27","P28")
limpieza99=("P1301","P1302","P1303","P1304","P14R","P2001","P2002","P2003","P2004",)

In [11]:
def drop_file(data,pregunta,valor):
    data = data[data[pregunta] != valor]
    return data

In [12]:
#Eliminación de NC-8 ó 88 y NS - 9 ó 99
for a in limpieza9:
    encuesta = drop_file(encuesta,a,8)
    encuesta = drop_file(encuesta,a,9)
for a in limpieza99:
    encuesta = drop_file(encuesta,a,88)
    encuesta = drop_file(encuesta,a,98)
    encuesta = drop_file(encuesta,a,99)


In [13]:
encuesta = drop_file(encuesta,"ESTUDIOS",7)
encuesta.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9731 entries, 0 to 16191
Data columns (total 29 columns):
P1          9731 non-null int64
P2          9731 non-null int64
P3          9731 non-null int64
P4          9731 non-null int64
P801        9731 non-null int64
P802        9731 non-null int64
P803        9731 non-null int64
P804        9731 non-null int64
P1301       9731 non-null int64
P1302       9731 non-null int64
P1303       9731 non-null int64
P1304       9731 non-null int64
P2001       9731 non-null int64
P2002       9731 non-null int64
P2003       9731 non-null int64
P2004       9731 non-null int64
P23         9731 non-null int64
TAMUNI      9731 non-null int64
ESTUDIOS    9731 non-null int64
CAPITAL     9731 non-null int64
CCAA        9731 non-null int64
P0A         9731 non-null int64
P14R        9731 non-null int64
P22         9731 non-null int64
P25         9731 non-null int64
P26         9731 non-null int64
P27         9731 non-null int64
P28         9731 non-null in

In [14]:
encuestaauto = drop_file(encuesta,"P19",98)
encuestaauto = drop_file(encuestaauto,"P19",99)

In [15]:
encuestaauto=encuestaauto.reset_index()

In [16]:
encuestaauto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9395 entries, 0 to 9394
Data columns (total 30 columns):
index       9395 non-null int64
P1          9395 non-null int64
P2          9395 non-null int64
P3          9395 non-null int64
P4          9395 non-null int64
P801        9395 non-null int64
P802        9395 non-null int64
P803        9395 non-null int64
P804        9395 non-null int64
P1301       9395 non-null int64
P1302       9395 non-null int64
P1303       9395 non-null int64
P1304       9395 non-null int64
P2001       9395 non-null int64
P2002       9395 non-null int64
P2003       9395 non-null int64
P2004       9395 non-null int64
P23         9395 non-null int64
TAMUNI      9395 non-null int64
ESTUDIOS    9395 non-null int64
CAPITAL     9395 non-null int64
CCAA        9395 non-null int64
P0A         9395 non-null int64
P14R        9395 non-null int64
P22         9395 non-null int64
P25         9395 non-null int64
P26         9395 non-null int64
P27         9395 non-null int

In [17]:
etiquetas=[0,1,2]
cortes = [0,3,6,10]
encuestaauto["ideologia"] = pd.cut(encuestaauto['P19'],cortes, labels=etiquetas)
encuestaauto["ideologia"] = pd.to_numeric(encuestaauto["ideologia"])

In [18]:
encuestaauto=encuestaauto.drop(columns="P19")
encuestaauto=encuestaauto.drop(columns="index")

In [19]:
variables_categoricas=["CAPITAL","CCAA","P0A","P14R","P22","P25","P26","P27","P28"]

In [20]:
encuesta2=encuestaauto.drop(columns=variables_categoricas)

In [21]:
encuesta_dum=encuestaauto[["CAPITAL","CCAA","P0A","P14R","P22","P25","P26","P27","P28"]]

In [22]:
encuesta_dum.head()

CAPITAL  CCAA  P0A  P14R  P22  P25  P26  P27  P28
0        1    16    1     2    1    2    2    1    1
1        1    16    1     1    2    3    1    1    1
2        1    16    1     3    2    1    5    2    1
3        1    16    1     2    1    1    4    1    1
4        1    16    1    12    1    1    5    2    1

In [23]:
scaler = StandardScaler()
encuestasta=encuesta2.loc[:,encuesta2.columns!='ideologia']
encuestasta = scaler.fit_transform(encuestasta)
encuestasta = pd.DataFrame(encuestasta)


/home/vicente/.local/lib/python3.5/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/home/vicente/.local/lib/python3.5/site-packages/sklearn/base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [24]:
encuestasta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9395 entries, 0 to 9394
Data columns (total 19 columns):
0     9395 non-null float64
1     9395 non-null float64
2     9395 non-null float64
3     9395 non-null float64
4     9395 non-null float64
5     9395 non-null float64
6     9395 non-null float64
7     9395 non-null float64
8     9395 non-null float64
9     9395 non-null float64
10    9395 non-null float64
11    9395 non-null float64
12    9395 non-null float64
13    9395 non-null float64
14    9395 non-null float64
15    9395 non-null float64
16    9395 non-null float64
17    9395 non-null float64
18    9395 non-null float64
dtypes: float64(19)
memory usage: 1.4 MB


In [25]:
colssincatX=["P1","P2","P3","P4","P801","P802","P803","P804","P1301","P1302","P1303","P1304","P2001","P2002","P2003","P2004","P23","TAMUNI","ESTUDIOS"]

In [26]:
len(colssincatX)

19

In [27]:
encuestasta.columns = colssincatX

In [28]:
encuesta_dum=pd.get_dummies(encuesta_dum, drop_first=True)

In [29]:
encuesta_dum.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9395 entries, 0 to 9394
Data columns (total 9 columns):
CAPITAL    9395 non-null int64
CCAA       9395 non-null int64
P0A        9395 non-null int64
P14R       9395 non-null int64
P22        9395 non-null int64
P25        9395 non-null int64
P26        9395 non-null int64
P27        9395 non-null int64
P28        9395 non-null int64
dtypes: int64(9)
memory usage: 660.7 KB


In [36]:
encuestatotal= encuesta_dum.merge(encuestasta,on=encuestasta.index)

In [40]:
encuestatotal= encuestatotal.drop(columns="key_0")

In [41]:
encuestatotal.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9395 entries, 0 to 9394
Data columns (total 28 columns):
CAPITAL     9395 non-null int64
CCAA        9395 non-null int64
P0A         9395 non-null int64
P14R        9395 non-null int64
P22         9395 non-null int64
P25         9395 non-null int64
P26         9395 non-null int64
P27         9395 non-null int64
P28         9395 non-null int64
P1          9395 non-null float64
P2          9395 non-null float64
P3          9395 non-null float64
P4          9395 non-null float64
P801        9395 non-null float64
P802        9395 non-null float64
P803        9395 non-null float64
P804        9395 non-null float64
P1301       9395 non-null float64
P1302       9395 non-null float64
P1303       9395 non-null float64
P1304       9395 non-null float64
P2001       9395 non-null float64
P2002       9395 non-null float64
P2003       9395 non-null float64
P2004       9395 non-null float64
P23         9395 non-null float64
TAMUNI      9395 non-null f

In [43]:
def modelos():
    X=encuestatotal
    y=encuestaauto["ideologia"]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
    
    #modelos
    lr = LogisticRegression(solver ='liblinear',max_iter=500)
    cls = svm.SVC(gamma='auto', probability=True)
    neigh3 = KNeighborsClassifier(n_neighbors=3)
    neigh5 = KNeighborsClassifier(n_neighbors=5)
    bosque=RandomForestClassifier(n_estimators=500, criterion='gini')
    gnb = GaussianNB()
    #tree = tree.DecisionTreeClassifier()
    svc = SVC(kernel='rbf', gamma='scale')
    gbc=GradientBoostingClassifier()

    #entrenando
    cls.fit(X_train, y_train)
    lr.fit(X_train, y_train)
    neigh3.fit(X_train, y_train) 
    neigh5.fit(X_train, y_train) 
    bosque.fit(X_train, y_train) 
    #tree.fit(X_train, y_train)
    gnb.fit(X_train,y_train)
    svc.fit(X_train,y_train)
    gbc.fit(X_train, y_train)



    
    
    y_predlr = lr.predict(X_test)
    y_predcls = cls.predict(X_test)
    y_pred_neigh3= neigh3.predict(X_test)
    y_pred_neigh5= neigh5.predict(X_test)
    y_pred_bosque= bosque.predict(X_test)
    #y_pred_tree= tree.predict(X_test)
    y_pred_gnd = gnb.predict(X_test)
    y_pred_svc = svc.predict(X_test)
    y_pred_gbc=gbc.predict(X_test)

    
    print("Accuracy lineal:",metrics.accuracy_score(y_test, y_predcls))
    print("Accuracy logistics:",metrics.accuracy_score(y_test, y_predlr))
    print("Accuracy neigh3:",metrics.accuracy_score(y_test, y_pred_neigh3))
    print("Accuracy neigh5:",metrics.accuracy_score(y_test, y_pred_neigh5))
    print("Accuracy bosque:",metrics.accuracy_score(y_test, y_pred_bosque))
    #print("Accuracy tree:",metrics.accuracy_score(y_test, y_pred_tree))
    print("Accuracy gnd:",metrics.accuracy_score(y_test, y_pred_gnd))
    print("Accuracy svc:",metrics.accuracy_score(y_test, y_pred_svc))
    print("Accuracy gbc:",metrics.accuracy_score(y_test, y_pred_gbc))
    


    # Your code here:
    print("matriz de confusion lineal","\n",confusion_matrix(y_test, y_predlr))
    print("matriz de confusion vecino3","\n",confusion_matrix(y_test, y_pred_neigh3))
    print("matriz de confusion vecino5","\n",confusion_matrix(y_test, y_pred_neigh5))
    print("matriz de confusion bosque","\n",confusion_matrix(y_test, y_pred_bosque))
    print("matriz de confusion gnd","\n",confusion_matrix(y_test, y_pred_gnd))
    print("matriz de confusion svc","\n",confusion_matrix(y_test, y_pred_svc))
    print("matriz de confusion gbc","\n", confusion_matrix(y_test, y_pred_gbc))

In [44]:
modelos()

/home/vicente/.local/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Accuracy lineal: 0.7301756253326237
Accuracy logistics: 0.7072911122937733
Accuracy neigh3: 0.6615220862160723
Accuracy neigh5: 0.6753592336349122
Accuracy bosque: 0.7482703565726451
Accuracy gnd: 0.6679084619478446
Accuracy svc: 0.7072911122937733
Accuracy gbc: 0.7621075039914849
matriz de confusion lineal 
 [[425 173   1]
 [170 673  70]
 [  4 132 231]]
matriz de confusion vecino3 
 [[396 197   6]
 [217 616  80]
 [ 11 125 231]]
matriz de confusion vecino5 
 [[404 194   1]
 [198 637  78]
 [  4 135 228]]
matriz de confusion bosque 
 [[448 150   1]
 [152 709  52]
 [  3 115 249]]
matriz de confusion gnd 
 [[493 101   5]
 [267 466 180]
 [  5  66 296]]
matriz de confusion svc 
 [[405 191   3]
 [165 684  64]
 [  4 123 240]]
matriz de confusion gbc 
 [[456 141   2]
 [143 712  58]
 [  4  99 264]]


In [46]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters = 3)
temp_kmeans = kmeans.fit(encuestatotal)
encuestatotal['labels'] = temp_kmeans.labels_
encuestatotal.labels.value_counts()

0    6743
2    1348
1    1304
Name: labels, dtype: int64

In [47]:
bla= pd.crosstab(encuestaauto.ideologia, encuestatotal.labels)
bla["total"]=bla.T.sum()
bla

labels        0    1    2  total
ideologia                       
0          2190  318  556   3064
1          3205  882  434   4521
2          1348  104  358   1810

In [48]:
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler

In [49]:
model_db = DBSCAN(eps=0.5)
model_db = model_db.fit(encuestatotal)

In [53]:
encuestatotal['labels_DBSCAN'] = model_db.labels_

In [54]:
bla2= pd.crosstab(encuestaauto.ideologia, encuestatotal.labels_DBSCAN)
bla2["total"]=bla2.T.sum()
bla2

labels_DBSCAN    -1  total
ideologia                 
0              3064   3064
1              4521   4521
2              1810   1810